/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectCreateImport } from './routes/project/create'
import { Route as ProjectIdIndexImport } from './routes/project/$id/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectCreateRoute = ProjectCreateImport.update({
  id: '/project/create',
  path: '/project/create',
  getParentRoute: () => rootRoute,
} as any)

const ProjectIdIndexRoute = ProjectIdIndexImport.update({
  id: '/project/$id/',
  path: '/project/$id/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/project/create': {
      id: '/project/create'
      path: '/project/create'
      fullPath: '/project/create'
      preLoaderRoute: typeof ProjectCreateImport
      parentRoute: typeof rootRoute
    }
    '/project/$id/': {
      id: '/project/$id/'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/create': typeof ProjectCreateRoute
  '/project/$id': typeof ProjectIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/create': typeof ProjectCreateRoute
  '/project/$id': typeof ProjectIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/project/create': typeof ProjectCreateRoute
  '/project/$id/': typeof ProjectIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/project/create' | '/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project/create' | '/project/$id'
  id: '__root__' | '/' | '/project/create' | '/project/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectCreateRoute: typeof ProjectCreateRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectCreateRoute: ProjectCreateRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/project/create",
        "/project/$id/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/project/create": {
      "filePath": "project/create.tsx"
    },
    "/project/$id/": {
      "filePath": "project/$id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
